/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Orders.OrderDirectory;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.GroceryAdminRole.ManageGroceryInventoryPanel;
import userinterface.GroceryAdminRole.ManageOrdersPanel;

/**
 *
 * @author Admin
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    EcoSystem ecosystem;
    DefaultTableModel model1;
    private UserAccount userAccount;
    private OrderDirectory orderDirectory;
    DefaultTableModel model;
    Customer cust;
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        ecosystem = system;
        cust = findCustomer();

        //valueLabel.setText(enterprise.getName());
        title2.setText("Welcome "+ cust.getName());
 }
    
     public Customer findCustomer() {
        for (int i = 0; i < ecosystem.getCustomerDirectory().getCustomerList().size(); i++) {
            if (ecosystem.getCustomerDirectory().getCustomerList().get(i).getAccountDetails().getUsername().equals(this.userAccount.getUsername())) {
                return ecosystem.getCustomerDirectory().getCustomerList().get(i);
            }
        }
        return null;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        grocerybutton = new javax.swing.JButton();
        maidbutton = new javax.swing.JButton();
        hotelbutton = new javax.swing.JButton();
        cardbutton = new javax.swing.JButton();
        Profile = new javax.swing.JButton();
        cartbutton = new javax.swing.JButton();
        container = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(10);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        grocerybutton.setBackground(new java.awt.Color(0, 0, 0));
        grocerybutton.setForeground(new java.awt.Color(255, 255, 255));
        grocerybutton.setText("Therapist");
        grocerybutton.setBorder(null);
        grocerybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grocerybuttonActionPerformed(evt);
            }
        });

        maidbutton.setBackground(new java.awt.Color(0, 0, 0));
        maidbutton.setForeground(new java.awt.Color(255, 255, 255));
        maidbutton.setText("Household");
        maidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maidbuttonActionPerformed(evt);
            }
        });

        hotelbutton.setBackground(new java.awt.Color(0, 0, 0));
        hotelbutton.setForeground(new java.awt.Color(255, 255, 255));
        hotelbutton.setText("Food");
        hotelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelbuttonActionPerformed(evt);
            }
        });

        cardbutton.setBackground(new java.awt.Color(0, 0, 0));
        cardbutton.setForeground(new java.awt.Color(255, 255, 255));
        cardbutton.setText("Add Card");
        cardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardbuttonActionPerformed(evt);
            }
        });

        Profile.setBackground(new java.awt.Color(0, 0, 0));
        Profile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 255, 255));
        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        cartbutton.setBackground(new java.awt.Color(0, 0, 0));
        cartbutton.setForeground(new java.awt.Color(255, 255, 255));
        cartbutton.setText("Cart");
        cartbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grocerybutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maidbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(hotelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(grocerybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hotelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maidbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cartbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(cardbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 255, 204));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("HEY THERE MY FRIEND");
        container.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 600, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        title.setBackground(new java.awt.Color(255, 255, 204));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Happy Animation GIF by Planet XOLO.gif"))); // NOI18N
        title.setText("jLabel3");
        container.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 490, 420));

        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void grocerybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grocerybuttonActionPerformed
         CustomerOrderTherapistPanel mm = new CustomerOrderTherapistPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
    jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_grocerybuttonActionPerformed

    private void maidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maidbuttonActionPerformed
        CustomerOrderMaidPanel mm = new CustomerOrderMaidPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);        // TODO add your handling code here:
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_maidbuttonActionPerformed

    private void hotelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelbuttonActionPerformed
        // TODO add your handling code here:
        CustomerHotelJPanel mm = new CustomerHotelJPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
//        userProcessContainer.add("manageNetworkJPanel",mm);
//        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_hotelbuttonActionPerformed

    private void cartbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbuttonActionPerformed
        // TODO add your handling code here:
        CustomerCart mm = new CustomerCart(userProcessContainer, userAccount, ecosystem, jSplitPane1, cust);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_cartbuttonActionPerformed

    private void cardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardbuttonActionPerformed
        // TODO add your handling code here:
        CustomerAddCardDetailsPanel mm = new CustomerAddCardDetailsPanel(userProcessContainer, userAccount, ecosystem, jSplitPane1);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_cardbuttonActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
        CustomerUpdateInformation mm = new CustomerUpdateInformation(userProcessContainer, userAccount, ecosystem, jSplitPane1);
        //        userProcessContainer.add("manageNetworkJPanel",mm);
        //        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        //        layout.next(userProcessContainer);
        jSplitPane1.setRightComponent(mm);
    }//GEN-LAST:event_ProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Profile;
    private javax.swing.JButton cardbutton;
    private javax.swing.JButton cartbutton;
    private javax.swing.JPanel container;
    private javax.swing.JButton grocerybutton;
    private javax.swing.JButton hotelbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton maidbutton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
